more major updates

diff --git a/aliases b/aliases
--- a/aliases
+++ b/aliases
@@ -94,26 +94,24 @@
 
   docker()
   {
-    if [[ "$1" == "cache" ]]; then
-      if [[ "$2" == "clean" ]]; then
-          echo Deleting dangling images
-          docker rmi $(docker images -q --no-trunc --filter "dangling=true") || true
-
-          echo Deleting dangling volumes
-          docker volume rm $(docker volume ls -q --filter "dangling=true") || true
+    if [[ "$1" == "clean" ]]; then
+    # functions for docker cleanup
+      if [[ "$2" == "all" ]]; then
+        docker kill $(docker ps -a -q)  # kill all
+        docker rm $(docker ps -a -q)  ## rm all
+      else  # remove images matching the grep
+        docker images | grep $2 | awk '{print $3}' | xargs docker rmi
       fi
+      echo Deleting dangling images
+      docker rmi $(docker images -q --no-trunc --filter "dangling=true") || true
+
+      echo Deleting dangling volumes
+      docker volume rm $(docker volume ls -q --filter "dangling=true") || true
     else
       echo $@ | xargs docker
     fi
   }
 
-# functions for docker cleanup
-  dko() { docker kill $1 && docker rm $1 }
-  drma() { docker rm $(docker ps -a -q) }
-  dkla() { docker kill $(docker ps -a -q) }
-  drmu() { docker rmi $(docker images -q --filter "dangling=true") }
-#  drmu() { docker rmi $(docker images -a | grep '^<none>' | awk '{print $3}') }
-  dcln() { dkla; drma; drmu }
   dxc() { docker exec -it $1 bash }
   dbounce() { docker-compose rm -f && docker-compose up }
 
@@ -135,7 +133,7 @@
   alias gcam='git commit -am'
   alias glog='git log --oneline --all --graph --decorate'
 
-  github-clone()  { git clone git@github.com:jnbnyc/$1.git }
+  github-clone()  { git clone git@github-jnbnyc:jnbnyc/$1.git }  #  ssh config specifies which key to use
   github-create() { curl -X POST -u jnbnyc -d "{\"name\": \"$1\" }" https://api.github.com/user/repos }
 
 # setup commit author
@@ -178,19 +176,19 @@
 
 
 # mach displays the basic information about the system
-mach()
-{
-    echo -e "\nMachine information:" ; uname -a
-    echo -e "\nUsers logged on:" ; w -h
-    echo -e "\nCurrent date :" ; date
-    echo -e "\nMachine status :" ; uptime
-    #echo -e "\nMemory status :" ; free
-    echo -e "\nFilesystem status :"; df -h
-}
+  mach()
+  {
+      echo -e "\nMachine information:" ; uname -a
+      echo -e "\nUsers logged on:" ; w -h
+      echo -e "\nCurrent date :" ; date
+      echo -e "\nMachine status :" ; uptime
+      #echo -e "\nMemory status :" ; free
+      echo -e "\nFilesystem status :"; df -h
+  }
 
 
 # generate a random password with a specified length, defaults to 8
-rpass()  {  tr -dc A-Za-z0-9_ < /dev/urandom | head -c ${1:=8} | xargs  }
+  rpass()  {  tr -dc A-Za-z0-9_ < /dev/urandom | head -c ${1:=8} | xargs  }
 
 
 # functions for akamai
